#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y haproxy
echo "ENABLE=1" >> /etc/default/haproxy
echo "
    global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon

    defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

    frontend myfrontend
        mode http
   
        # Receive HTTP traffic on all IP addresses assigned to the server at port 80
        bind :80
        default_backend web_servers
        
        backend web_servers
        mode http
        balance roundrobin
        server 516997-web-01 54.237.101.82 check
        server 516997-web-02 18.235.243.156 check
        " >haproxy.cfg
sudo mv -f haproxy.cfg /etc/haproxy
sudo systemctl restart haproxy
