#!/usr/bin/env bash
# why you no love me

case "$1" in
  start)
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    kill -TERM $(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    kill -TERM $(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
